apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-wordpress-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: app-wordpress-volume
