apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-mysql-claim
spec:
  storageClassName: manual 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi 
  volumeName: db-mysql-volume
