apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
  labels:
    app: {{ .Values.db.app }}
spec:
  ports:
    - port: {{ .Values.db.service.port }} 
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
